package co.com.juan.invbill.enums;

/**
 * @author Juan Felipe
 */
public enum SessionEnum {

    LOGIN, PURCHASE_HEADER_DETAIL, PURCHASE_HEADERS, RETURN_HEADER_DETAIL, INVOICE_HEADER_DETAIL,
    RETURN_HEADERS, INVOICE_HEADERS, LAST_LOGIN, SPRING_SECURITY_CONTEXT

}
