package co.com.juan.invbill.enums;

/**
 * @author Juan Felipe
 *
 */
public enum SessionEnum {

	LOGIN, COMPRA_CABECERA_DETALLE, COMPRA_CABECERAS, DEVOLUCION_CABECERA_DETALLE, FACTURA_CABECERA_DETALLE,
	DEVOLUCION_CABECERAS, FACTURA_CABECERAS, LAST_LOGIN, SPRING_SECURITY_CONTEXT;

}
