package co.com.juan.invbill.model;
// Generated 10/07/2017 10:38:42 PM by Hibernate Tools 4.0.1.Final

/**
 * CompraDetalleId generated by hbm2java
 */
public class CompraDetalleId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer idProveedorApp;
	private String idFacturaCompra;
	private Integer idProducto;

	public CompraDetalleId() {
	}

	public CompraDetalleId(Integer idProveedorApp, String idFacturaCompra, Integer idProducto) {
		this.idProveedorApp = idProveedorApp;
		this.idFacturaCompra = idFacturaCompra;
		this.idProducto = idProducto;
	}

	public Integer getIdProveedorApp() {
		return this.idProveedorApp;
	}

	public void setIdProveedorApp(Integer idProveedorApp) {
		this.idProveedorApp = idProveedorApp;
	}

	public String getIdFacturaCompra() {
		return this.idFacturaCompra;
	}

	public void setIdFacturaCompra(String idFacturaCompra) {
		this.idFacturaCompra = idFacturaCompra;
	}

	public Integer getIdProducto() {
		return this.idProducto;
	}

	public void setIdProducto(Integer idProducto) {
		this.idProducto = idProducto;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CompraDetalleId))
			return false;
		CompraDetalleId castOther = (CompraDetalleId) other;

		return (this.getIdProveedorApp() == castOther.getIdProveedorApp())
				&& (this.getIdFacturaCompra() == castOther.getIdFacturaCompra())
				&& (this.getIdProducto() == castOther.getIdProducto());
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdProveedorApp();
		result = 37 * result + ((this.getIdFacturaCompra() == null) ? 0 : this.getIdFacturaCompra().hashCode());
		result = 37 * result + this.getIdProducto();
		return result;
	}

}
