package co.com.juan.invbill.model;

import java.io.Serializable;
import java.util.Objects;

/**
 * DevolucionDetalleId generated by hbm2java
 */
public class DevolucionDetalleId implements Serializable {

    private Integer idFactura;
    private Integer idProducto;

    public DevolucionDetalleId() {
    }

    public DevolucionDetalleId(Integer idFactura, Integer idProducto) {
        this.idFactura = idFactura;
        this.idProducto = idProducto;
    }

    public Integer getIdFactura() {
        return this.idFactura;
    }

    public void setIdFactura(Integer idFactura) {
        this.idFactura = idFactura;
    }

    public Integer getIdProducto() {
        return this.idProducto;
    }

    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }

    @Override
    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof DevolucionDetalleId))
            return false;
        DevolucionDetalleId castOther = (DevolucionDetalleId) other;

        return (Objects.equals(this.getIdFactura(), castOther.getIdFactura())) && (Objects.equals(this.getIdProducto(), castOther.getIdProducto()));
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getIdFactura();
        result = 37 * result + this.getIdProducto();
        return result;
    }

}
