package co.com.juan.invbill.model;

import java.util.Date;

/**
 * LoginApp generated by Java
 */
public class LoginApp {

    private String idLoginApp;
    private Date ultimoLogin;
    private String idSession;

    public static Builder builder() {
        return new Builder();
    }

    public String getIdLoginApp() {
        return this.idLoginApp;
    }

    public void setIdLoginApp(String idLoginApp) {
        this.idLoginApp = idLoginApp;
    }

    public Date getUltimoLogin() {
        return this.ultimoLogin;
    }

    public void setUltimoLogin(Date ultimoLogin) {
        this.ultimoLogin = ultimoLogin;
    }

    public String getIdSession() {
        return this.idSession;
    }

    public void setIdSession(String idSession) {
        this.idSession = idSession;
    }

    public static final class Builder {

        private final LoginApp loginApp;

        private Builder() {
            this.loginApp = new LoginApp();
        }

        public Builder idLoginApp(String idLoginApp) {
            this.loginApp.setIdLoginApp(idLoginApp);
            return this;
        }

        public Builder idSession(String idSession) {
            this.loginApp.setIdSession(idSession);
            return this;
        }

        public LoginApp build() {
            return this.loginApp;
        }
    }

}
