package co.com.juan.invbill.model;

import java.util.HashSet;
import java.util.Set;

import co.com.juan.invbill.enums.StatusEnum;

/**
 * RolApp generated by hbm2java
 */
public class RolApp {

    private Integer idRolApp;
    private String rol;
    private StatusEnum estado;
    private transient Set<Object> usuarioApps = new HashSet<>(0);

    public static Builder builder() {
        return new Builder();
    }

    public Integer getIdRolApp() {
        return this.idRolApp;
    }

    public void setIdRolApp(Integer idRolApp) {
        this.idRolApp = idRolApp;
    }

    public String getRol() {
        return this.rol;
    }

    public void setRol(String rol) {
        this.rol = rol;
    }

    public StatusEnum getEstado() {
        return this.estado;
    }

    public void setEstado(StatusEnum estado) {
        this.estado = estado;
    }

    public Set<Object> getUsuarioApps() {
        return this.usuarioApps;
    }

    public void setUsuarioApps(Set<Object> usuarioApps) {
        this.usuarioApps = usuarioApps;
    }

    public static final class Builder {

        private final RolApp rolApp;

        private Builder() {
            this.rolApp = new RolApp();
        }

        public Builder idRolApp(Integer idRolApp) {
            this.rolApp.setIdRolApp(idRolApp);
            return this;
        }

        public Builder rol(String rol) {
            this.rolApp.setRol(rol);
            return this;
        }

        public Builder estado(StatusEnum estado) {
            this.rolApp.setEstado(estado);
            return this;
        }

        public RolApp build() {
            return this.rolApp;
        }
    }

}
