package co.com.juan.invbill.model;
// Generated 11-feb-2017 9:50:57 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import co.com.juan.invbill.enums.EstadoEnum;

/**
 * RolApp generated by hbm2java
 */
public class RolApp implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer idRolApp;
	private String rol;
	private EstadoEnum estado;
	private transient Set<Object> usuarioApps = new HashSet<>(0);

	public RolApp() {
	}

	public RolApp(String rol, EstadoEnum estado) {
		this.rol = rol;
		this.estado = estado;
	}

	public Integer getIdRolApp() {
		return this.idRolApp;
	}

	public void setIdRolApp(Integer idRolApp) {
		this.idRolApp = idRolApp;
	}

	public String getRol() {
		return this.rol;
	}

	public void setRol(String rol) {
		this.rol = rol;
	}

	public EstadoEnum getEstado() {
		return this.estado;
	}

	public void setEstado(EstadoEnum estado) {
		this.estado = estado;
	}

	public Set<Object> getUsuarioApps() {
		return this.usuarioApps;
	}

	public void setUsuarioApps(Set<Object> usuarioApps) {
		this.usuarioApps = usuarioApps;
	}

}
