package co.com.juan.invbill.model;

import java.util.Date;

/**
 * StockProducto generated by hbm2java
 */
public class StockProducto {

    private Integer idStockProducto;
    private Producto producto;
    private Integer stock;
    private Integer precioCompra;
    private Integer precioVenta;
    private Date fechaCreacion;

    public static Builder builder() {
        return new Builder();
    }

    public Integer getIdStockProducto() {
        return this.idStockProducto;
    }

    public void setIdStockProducto(Integer idStockProducto) {
        this.idStockProducto = idStockProducto;
    }

    public Producto getProducto() {
        return this.producto;
    }

    public void setProducto(Producto producto) {
        this.producto = producto;
    }

    public Integer getStock() {
        return this.stock;
    }

    public void setStock(Integer stock) {
        this.stock = stock;
    }

    public Integer getPrecioCompra() {
        return this.precioCompra;
    }

    public void setPrecioCompra(Integer precioCompra) {
        this.precioCompra = precioCompra;
    }

    public Integer getPrecioVenta() {
        return this.precioVenta;
    }

    public void setPrecioVenta(Integer precioVenta) {
        this.precioVenta = precioVenta;
    }

    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    public static class Builder {

        private final StockProducto stockProducto;

        private Builder() {
            this.stockProducto = new StockProducto();
        }

        public Builder producto(Producto producto) {
            this.stockProducto.setProducto(producto);
            return this;
        }

        public StockProducto build() {
            return this.stockProducto;
        }
    }

}
