package co.com.juan.tcr.model;
// Generated 27/10/2017 11:00:27 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AppMenu generated by hbm2java
 */
public class AppMenu implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private String idAppMenu;
	private AppMenu menu;
	private String valor;
	private String salida;
	private String icono;
	private String orden;
	private Date fechaCreacion;
	private transient Set<Object> appMenus = new HashSet<>(0);

	public AppMenu() {
	}

	public AppMenu(String idAppMenu, String valor) {
		this.idAppMenu = idAppMenu;
		this.valor = valor;
	}

	public AppMenu(String idAppMenu, AppMenu appMenu, String valor, String salida, String icono, String orden,
			Date fechaCreacion) {
		this.idAppMenu = idAppMenu;
		this.setMenu(appMenu);
		this.valor = valor;
		this.salida = salida;
		this.icono = icono;
		this.orden = orden;
		this.fechaCreacion = fechaCreacion;
	}

	public String getIdAppMenu() {
		return this.idAppMenu;
	}

	public void setIdAppMenu(String idAppMenu) {
		this.idAppMenu = idAppMenu;
	}

	public AppMenu getMenu() {
		return menu;
	}

	public void setMenu(AppMenu menu) {
		this.menu = menu;
	}

	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

	public String getSalida() {
		return this.salida;
	}

	public void setSalida(String salida) {
		this.salida = salida;
	}

	public String getIcono() {
		return this.icono;
	}

	public void setIcono(String icono) {
		this.icono = icono;
	}

	public String getOrden() {
		return orden;
	}

	public void setOrden(String orden) {
		this.orden = orden;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public Set<Object> getAppMenus() {
		return this.appMenus;
	}

	public void setAppMenus(Set<Object> appMenus) {
		this.appMenus = appMenus;
	}

}
