package co.com.juan.tcr.model;
// Generated 8/07/2017 10:57:33 AM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import co.com.juan.tcr.enums.EstadosAppEnum;

/**
 * ClienteApp generated by hbm2java
 */
public class ClienteApp implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer idClienteApp;
	private String razonSocial;
	private EstadosAppEnum estado;
	private Date fechaCreacion;
	private transient Set<Object> facturaCabeceras = new HashSet<>(0);

	public ClienteApp() {
	}

	public ClienteApp(Integer idClienteApp, String razonSocial, EstadosAppEnum estado) {
		this.idClienteApp = idClienteApp;
		this.razonSocial = razonSocial;
		this.estado = estado;
	}

	public Integer getIdClienteApp() {
		return this.idClienteApp;
	}

	public void setIdClienteApp(Integer idClienteApp) {
		this.idClienteApp = idClienteApp;
	}

	public String getRazonSocial() {
		return this.razonSocial;
	}

	public void setRazonSocial(String razonSocial) {
		this.razonSocial = razonSocial;
	}

	public EstadosAppEnum getEstado() {
		return this.estado;
	}

	public void setEstado(EstadosAppEnum estado) {
		this.estado = estado;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public Set<Object> getFacturaCabeceras() {
		return facturaCabeceras;
	}

	public void setFacturaCabeceras(Set<Object> facturaCabeceras) {
		this.facturaCabeceras = facturaCabeceras;
	}

}
