package co.com.juan.tcr.model;
// Generated 10/07/2017 10:38:42 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;

/**
 * CompraDetalle generated by hbm2java
 */
public class CompraDetalle implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private CompraDetalleId id;
	private CompraCabecera compraCabecera;
	private Producto producto;
	private Integer cantidad;
	private Double precioCompra;
	private Double valorIva;
	private Date fechaCreacion;
	private Boolean discriminarIva = true;

	public CompraDetalle() {
	}

	public CompraDetalle(CompraDetalleId id, CompraCabecera compraCabecera, Producto producto, Integer cantidad,
			Double precioCompra, Double valorIva) {
		this.id = id;
		this.compraCabecera = compraCabecera;
		this.producto = producto;
		this.cantidad = cantidad;
		this.precioCompra = precioCompra;
		this.valorIva = valorIva;
	}

	public CompraDetalle(CompraDetalleId id, CompraCabecera compraCabecera, Producto producto, Integer cantidad,
			Double precioCompra, Double valorIva, Date fechaCreacion) {
		this.id = id;
		this.compraCabecera = compraCabecera;
		this.producto = producto;
		this.cantidad = cantidad;
		this.precioCompra = precioCompra;
		this.valorIva = valorIva;
		this.fechaCreacion = fechaCreacion;
	}

	public CompraDetalleId getId() {
		return this.id;
	}

	public void setId(CompraDetalleId id) {
		this.id = id;
	}

	public CompraCabecera getCompraCabecera() {
		return this.compraCabecera;
	}

	public void setCompraCabecera(CompraCabecera compraCabecera) {
		this.compraCabecera = compraCabecera;
	}

	public Integer getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

	public Double getPrecioCompra() {
		return this.precioCompra;
	}

	public void setPrecioCompra(Double precioCompra) {
		this.precioCompra = precioCompra;
	}

	public Double getValorIva() {
		return this.valorIva;
	}

	public void setValorIva(Double valorIva) {
		this.valorIva = valorIva;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public Producto getProducto() {
		return producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	/**
	 * @return the discriminarIva
	 */
	public Boolean getDiscriminarIva() {
		return discriminarIva;
	}

	/**
	 * @param discriminarIva
	 *            the discriminarIva to set
	 */
	public void setDiscriminarIva(Boolean discriminarIva) {
		this.discriminarIva = discriminarIva;
	}

}
