package co.com.juan.tcr.model;
// Generated 25-mar-2017 1:19:16 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DevolucionCabecera generated by hbm2java
 */
public class DevolucionCabecera implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer idFactura;
	private Double valorNeto;
	private Double valorIva;
	private Integer valorTotal;
	private String usuarioCreacion;
	private Date fechaCreacion;
	private transient Set<Object> devolucionDetalles = new HashSet<>(0);

	public DevolucionCabecera() {
	}

	public DevolucionCabecera(Double valorNeto, Double valorIva, Integer valorTotal, String usuarioCreacion) {
		this.valorNeto = valorNeto;
		this.valorIva = valorIva;
		this.valorTotal = valorTotal;
		this.usuarioCreacion = usuarioCreacion;
	}

	public Integer getIdFactura() {
		return this.idFactura;
	}

	public void setIdFactura(Integer idFactura) {
		this.idFactura = idFactura;
	}

	public Double getValorNeto() {
		return this.valorNeto;
	}

	public void setValorNeto(Double valorNeto) {
		this.valorNeto = valorNeto;
	}

	public Double getValorIva() {
		return this.valorIva;
	}

	public void setValorIva(Double valorIva) {
		this.valorIva = valorIva;
	}

	public Integer getValorTotal() {
		return this.valorTotal;
	}

	public void setValorTotal(Integer valorTotal) {
		this.valorTotal = valorTotal;
	}

	public String getUsuarioCreacion() {
		return this.usuarioCreacion;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public Set<Object> getDevolucionDetalles() {
		return this.devolucionDetalles;
	}

	public void setDevolucionDetalles(Set<Object> devolucionDetalles) {
		this.devolucionDetalles = devolucionDetalles;
	}

}
