package co.com.juan.tcr.model;
// Generated 25-mar-2017 1:19:16 by Hibernate Tools 4.0.0

/**
 * FacturaDetalleId generated by hbm2java
 */
public class FacturaDetalleId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer idFactura;
	private Integer idProducto;

	public FacturaDetalleId() {
	}

	public FacturaDetalleId(Integer idFactura, Integer idProducto) {
		this.idFactura = idFactura;
		this.idProducto = idProducto;
	}

	public Integer getIdFactura() {
		return this.idFactura;
	}

	public void setIdFactura(Integer idFactura) {
		this.idFactura = idFactura;
	}

	public Integer getIdProducto() {
		return this.idProducto;
	}

	public void setIdProducto(Integer idProducto) {
		this.idProducto = idProducto;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FacturaDetalleId))
			return false;
		FacturaDetalleId castOther = (FacturaDetalleId) other;

		return (this.getIdFactura() == castOther.getIdFactura()) && (this.getIdProducto() == castOther.getIdProducto());
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdFactura();
		result = 37 * result + this.getIdProducto();
		return result;
	}

}
