package co.com.juan.invbill.model;
// Generated 11-feb-2017 9:50:57 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import co.com.juan.invbill.enums.EstadoEnum;

/**
 * CategoriaProducto generated by hbm2java
 */
public class CategoriaProducto implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer idCategoria;
	private String categoria;
	private EstadoEnum estado;
	private Date fechaCreacion;
	private transient Set<Object> productos = new HashSet<>(0);

	public CategoriaProducto() {
	}

	public CategoriaProducto(String categoria, EstadoEnum estado, Date fechaCreacion) {
		this.categoria = categoria;
		this.estado = estado;
		this.fechaCreacion = fechaCreacion;
	}

	public Integer getIdCategoria() {
		return this.idCategoria;
	}

	public void setIdCategoria(Integer idCategoria) {
		this.idCategoria = idCategoria;
	}

	public String getCategoria() {
		return this.categoria;
	}

	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}

	public EstadoEnum getEstado() {
		return this.estado;
	}

	public void setEstado(EstadoEnum estado) {
		this.estado = estado;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public Set<Object> getProductos() {
		return this.productos;
	}

	public void setProductos(Set<Object> productos) {
		this.productos = productos;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((categoria == null) ? 0 : categoria.hashCode());
		result = prime * result + ((idCategoria == null) ? 0 : idCategoria.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		CategoriaProducto other = (CategoriaProducto) obj;
		if (categoria == null) {
			if (other.categoria != null)
				return false;
		} else if (!categoria.equals(other.categoria)) {
			return false;
		}
		if (idCategoria == null) {
			if (other.idCategoria != null)
				return false;
		} else if (!idCategoria.equals(other.idCategoria)) {
			return false;
		}
		return true;
	}

}
