package co.com.juan.invbill.model;
// Generated 10/07/2017 10:38:42 PM by Hibernate Tools 4.0.1.Final

/**
 * CompraCabeceraId generated by hbm2java
 */
public class CompraCabeceraId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private String idFacturaCompra;
	private Integer idProveedorApp;

	public CompraCabeceraId() {
	}

	public CompraCabeceraId(String idFacturaCompra, Integer idProveedorApp) {
		this.idFacturaCompra = idFacturaCompra;
		this.idProveedorApp = idProveedorApp;
	}

	public String getIdFacturaCompra() {
		return this.idFacturaCompra;
	}

	public void setIdFacturaCompra(String idFacturaCompra) {
		this.idFacturaCompra = idFacturaCompra;
	}

	public Integer getIdProveedorApp() {
		return this.idProveedorApp;
	}

	public void setIdProveedorApp(Integer idProveedorApp) {
		this.idProveedorApp = idProveedorApp;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idFacturaCompra == null) ? 0 : idFacturaCompra.hashCode());
		result = prime * result + ((idProveedorApp == null) ? 0 : idProveedorApp.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		CompraCabeceraId other = (CompraCabeceraId) obj;
		if (idFacturaCompra == null) {
			if (other.idFacturaCompra != null)
				return false;
		} else if (!idFacturaCompra.equals(other.idFacturaCompra)) {
			return false;
		}
		if (idProveedorApp == null) {
			if (other.idProveedorApp != null)
				return false;
		} else if (!idProveedorApp.equals(other.idProveedorApp)) {
			return false;
		}
		return true;
	}

}
