package co.com.juan.invbill.model;
// Generated 25-mar-2017 1:19:16 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * FacturaDetalle generated by hbm2java
 */
public class FacturaDetalle implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private FacturaDetalleId id;
	private FacturaCabecera facturaCabecera;
	private Producto producto;
	private Integer cantidad;
	private Double precioVenta;
	private Double valorIva;
	private Date fechaCreacion;

	public FacturaDetalle() {
	}

	public FacturaDetalle(FacturaDetalleId id, FacturaCabecera facturaCabecera, Producto producto, Integer cantidad,
			Double precioVenta, Double valorIva) {
		this.id = id;
		this.facturaCabecera = facturaCabecera;
		this.producto = producto;
		this.cantidad = cantidad;
		this.precioVenta = precioVenta;
		this.valorIva = valorIva;
	}

	public FacturaDetalle(FacturaDetalleId id, FacturaCabecera facturaCabecera, Producto producto, Integer cantidad,
			Double precioVenta, double valorIva, Date fechaCreacion) {
		this.id = id;
		this.facturaCabecera = facturaCabecera;
		this.producto = producto;
		this.cantidad = cantidad;
		this.precioVenta = precioVenta;
		this.valorIva = valorIva;
		this.fechaCreacion = fechaCreacion;
	}

	public FacturaDetalleId getId() {
		return this.id;
	}

	public void setId(FacturaDetalleId id) {
		this.id = id;
	}

	public FacturaCabecera getFacturaCabecera() {
		return this.facturaCabecera;
	}

	public void setFacturaCabecera(FacturaCabecera facturaCabecera) {
		this.facturaCabecera = facturaCabecera;
	}

	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	public Integer getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

	public Double getPrecioVenta() {
		return this.precioVenta;
	}

	public void setPrecioVenta(Double precioVenta) {
		this.precioVenta = precioVenta;
	}

	public Double getValorIva() {
		return this.valorIva;
	}

	public void setValorIva(Double valorIva) {
		this.valorIva = valorIva;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

}
