package co.com.juan.invbill.model;

// Generated 11-feb-2017 9:50:57 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import co.com.juan.invbill.enums.EstadoEnum;

/**
 * Producto generated by hbm2java
 */
public class Producto implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer idProducto;
	private CategoriaProducto categoriaProducto;
	private TipoUnidadMedida tipoUnidadMedida;
	private String desProducto;
	private EstadoEnum estado;
	private Date fechaCreacion;
	private Double medida;
	private transient Set<Object> stockProductos = new HashSet<>(0);
	private transient Set<Object> facturaDetalles = new HashSet<>(0);
	private transient Set<Object> compraDetalles = new HashSet<>(0);
	private transient Set<Object> devolucionDetalles = new HashSet<>(0);

	public Producto() {
	}

	public Producto(CategoriaProducto categoriaProducto, TipoUnidadMedida tipoUnidadMedida, String desProducto,
			EstadoEnum estado, Date fechaCreacion, Double medida) {
		this.tipoUnidadMedida = tipoUnidadMedida;
		this.categoriaProducto = categoriaProducto;
		this.desProducto = desProducto;
		this.estado = estado;
		this.fechaCreacion = fechaCreacion;
		this.medida = medida;
	}

	public Integer getIdProducto() {
		return this.idProducto;
	}

	public void setIdProducto(Integer idProducto) {
		this.idProducto = idProducto;
	}

	public CategoriaProducto getCategoriaProducto() {
		return this.categoriaProducto;
	}

	public void setCategoriaProducto(CategoriaProducto categoriaProducto) {
		this.categoriaProducto = categoriaProducto;
	}

	public TipoUnidadMedida getTipoUnidadMedida() {
		return this.tipoUnidadMedida;
	}

	public void setTipoUnidadMedida(TipoUnidadMedida tipoUnidadMedida) {
		this.tipoUnidadMedida = tipoUnidadMedida;
	}

	public String getProducto() {
		return this.desProducto;
	}

	public void setProducto(String producto) {
		this.desProducto = producto;
	}

	public EstadoEnum getEstado() {
		return this.estado;
	}

	public void setEstado(EstadoEnum estado) {
		this.estado = estado;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public Double getMedida() {
		return this.medida;
	}

	public void setMedida(Double medida) {
		this.medida = medida;
	}

	public Set<Object> getStockProductos() {
		return stockProductos;
	}

	public void setStockProductos(Set<Object> stockProductos) {
		this.stockProductos = stockProductos;
	}

	public Set<Object> getFacturaDetalles() {
		return this.facturaDetalles;
	}

	public void setFacturaDetalles(Set<Object> facturaDetalles) {
		this.facturaDetalles = facturaDetalles;
	}

	public Set<Object> getCompraDetalles() {
		return compraDetalles;
	}

	public void setCompraDetalles(Set<Object> compraDetalles) {
		this.compraDetalles = compraDetalles;
	}

	public Set<Object> getDevolucionDetalles() {
		return devolucionDetalles;
	}

	public void setDevolucionDetalles(Set<Object> devolucionDetalles) {
		this.devolucionDetalles = devolucionDetalles;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((categoriaProducto == null) ? 0 : categoriaProducto.hashCode());
		result = prime * result + ((desProducto == null) ? 0 : desProducto.hashCode());
		result = prime * result + ((idProducto == null) ? 0 : idProducto.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Producto other = (Producto) obj;
		if (categoriaProducto == null) {
			if (other.categoriaProducto != null) {
				return false;
			}
		} else if (!categoriaProducto.equals(other.categoriaProducto)) {
			return false;
		}
		if (desProducto == null) {
			if (other.desProducto != null) {
				return false;
			}
		} else if (!desProducto.equals(other.desProducto)) {
			return false;
		}
		if (idProducto == null) {
			if (other.idProducto != null) {
				return false;
			}
		} else if (!idProducto.equals(other.idProducto)) {
			return false;
		}
		return true;
	}

}
