package co.com.juan.invbill.model;
// Generated 8/07/2017 10:57:33 AM by Hibernate Tools 4.0.1.Final

import java.math.BigInteger;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import co.com.juan.invbill.enums.EstadoEnum;

/**
 * ProveedorApp generated by hbm2java
 */
public class ProveedorApp implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer idProveedorApp;
	private Integer codVerificacion;
	private String razonSocial;
	private String direccion;
	private Integer telefono;
	private Integer telefonoExt;
	private BigInteger celular;
	private EstadoEnum estado;
	private Date fechaCreacion;
	private transient Set<Object> compraCabeceras = new HashSet<>(0);

	public ProveedorApp() {
	}

	public ProveedorApp(Integer idProveedorApp, Integer codVerificacion, String razonSocial, EstadoEnum estado) {
		this.idProveedorApp = idProveedorApp;
		this.codVerificacion = codVerificacion;
		this.razonSocial = razonSocial;
		this.estado = estado;
	}

	public Integer getIdProveedorApp() {
		return this.idProveedorApp;
	}

	public void setIdProveedorApp(Integer idProveedorApp) {
		this.idProveedorApp = idProveedorApp;
	}

	public Integer getCodVerificacion() {
		return this.codVerificacion;
	}

	public void setCodVerificacion(Integer codVerificacion) {
		this.codVerificacion = codVerificacion;
	}

	public String getRazonSocial() {
		return this.razonSocial;
	}

	public void setRazonSocial(String razonSocial) {
		this.razonSocial = razonSocial;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public Integer getTelefono() {
		return this.telefono;
	}

	public void setTelefono(Integer telefono) {
		this.telefono = telefono;
	}

	public Integer getTelefonoExt() {
		return this.telefonoExt;
	}

	public void setTelefonoExt(Integer telefonoExt) {
		this.telefonoExt = telefonoExt;
	}

	public BigInteger getCelular() {
		return this.celular;
	}

	public void setCelular(BigInteger celular) {
		this.celular = celular;
	}

	public EstadoEnum getEstado() {
		return this.estado;
	}

	public void setEstado(EstadoEnum estado) {
		this.estado = estado;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public Set<Object> getCompraCabeceras() {
		return compraCabeceras;
	}

	public void setCompraCabeceras(Set<Object> compraCabeceras) {
		this.compraCabeceras = compraCabeceras;
	}

}
