package co.com.juan.invbill.model;

// Generated 23/08/2018 09:46:54 AM by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;

import co.com.juan.invbill.enums.EstadosAppEnum;

/**
 * TipoUnidadMedida generated by hbm2java
 */
public class TipoUnidadMedida implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer idUnidadMedida;
	private String tipoUnidad;
	private String unidad;
	private EstadosAppEnum estado;
	private transient Set<Object> productos = new HashSet<>(0);

	public TipoUnidadMedida() {
	}

	public TipoUnidadMedida(Integer idUnidadMedida, String tipoUnidad, String unidad, EstadosAppEnum estado) {
		this.idUnidadMedida = idUnidadMedida;
		this.tipoUnidad = tipoUnidad;
		this.unidad = unidad;
		this.estado = estado;
	}

	public Integer getIdUnidadMedida() {
		return this.idUnidadMedida;
	}

	public void setIdUnidadMedida(Integer idUnidadMedida) {
		this.idUnidadMedida = idUnidadMedida;
	}

	public String getTipoUnidad() {
		return this.tipoUnidad;
	}

	public void setTipoUnidad(String tipoUnidad) {
		this.tipoUnidad = tipoUnidad;
	}

	public String getUnidad() {
		return this.unidad;
	}

	public void setUnidad(String unidad) {
		this.unidad = unidad;
	}

	public EstadosAppEnum getEstado() {
		return this.estado;
	}

	public void setEstado(EstadosAppEnum estado) {
		this.estado = estado;
	}

	public Set<Object> getProductos() {
		return this.productos;
	}

	public void setProductos(Set<Object> productos) {
		this.productos = productos;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((idUnidadMedida == null) ? 0 : idUnidadMedida.hashCode());
		result = prime * result + ((tipoUnidad == null) ? 0 : tipoUnidad.hashCode());
		result = prime * result + ((unidad == null) ? 0 : unidad.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		TipoUnidadMedida other = (TipoUnidadMedida) obj;
		if (idUnidadMedida == null) {
			if (other.idUnidadMedida != null)
				return false;
		} else if (!idUnidadMedida.equals(other.idUnidadMedida)) {
			return false;
		}
		if (tipoUnidad == null) {
			if (other.tipoUnidad != null)
				return false;
		} else if (!tipoUnidad.equals(other.tipoUnidad)) {
			return false;
		}
		if (unidad == null) {
			if (other.unidad != null)
				return false;
		} else if (!unidad.equals(other.unidad)) {
			return false;
		}
		return true;
	}

}
